### ISSUE TITLE
Update needed to support future fody versions

### ISSUE THREAD

**Issue by tom-englert** [jasonwoods-7/Vandelay#3]
As of Fody 3.2.5 the strategy to lookup weavers has changed:
https://github.com/Fody/Fody/wiki/AddinSearchPaths

The legacy lookup will be no longer supported in the next versions of Fody, so this weaver needs to add the props file to the NuGet package to be usable with future Fody versions.

**Comment by jasonwoods-7** [comment]
Updated to Fody 4.0.2 for 0.7.0 release.
